version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: ai-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - /home/fsayush100/ai_docs_mongo_data:/data/db
    networks:
      - ai_dock_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - ai_dock_network

volumes:
  qdrant_data:

networks:
  ai_dock_network:
    driver: bridge
